### PR TITLE
Remove operation

### LINKED ISSUE #573: MANAGE - remove operation from job (B: _pts F: 4pts)
User story
-
As a user I want to remove an operation from a job in the expanded view.

Key components
-
- [ ] Operations can only be removed from jobs that are not started
- [ ] Remove operation icon on left of each operation line in expanded view

API calls
-
- [ ] Ex. "get jobs with specific attributes (job type or operation type)"

Screenshots/additional context
-
Screen Shot 2021-03-08 at 9 59 27 AM

### PR DESCRIPTION
**Pull request by marikoja**
Resolves #573 
Operations with scheduled status can be removed. 
Only show cancel job on jobs that are not started.

### CODE REVIEW

**Comment by bjkeller** [comment]
Should the merge target for this be v3-refactor?

**Comment by marikoja** [comment]
Ahh yeah it probably should be.

**Comment by cashmonger** [comment]
This is working the way it was intended and solves the issues -- you can see the remove button if an op is scheduled, but not if it's running. I am wondering, though, if we want the button to be visible for the other non-running statuses (pending, delayed, waiting, planning, primed, and error). That's more a question for the end users though. As for now, the remove button is only visible for status "scheduled" and not visible for any of the other statuses.

**Comment by marikoja** [comment]
I created a new issue related to the question in @cashmonger's  comment.

**Pull request merged**
